
name: Staging Deployment & Validation

on:
  push:
    branches: [develop, staging]
  pull_request:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      
      - run: yarn install --frozen-lockfile
      - run: yarn tsc --noEmit
      - run: yarn lint
      
  build-and-test:
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          
      - run: yarn install --frozen-lockfile
      - run: yarn build
      
      # Lighthouse CI for performance validation
      - run: npm install -g @lhci/cli@0.12.x
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v4
      - uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          
      # Post-deployment validation
      - name: Smoke Test Staging
        run: |
          curl -f ${{ env.STAGING_URL }}/api/health || exit 1
          curl -f ${{ env.STAGING_URL }}/api/social-embeds || exit 1
          curl -f ${{ env.STAGING_URL }}/api/media || exit 1
          curl -f ${{ env.STAGING_URL }}/api/homepage-blocks || exit 1
