/**
 * SEO Agent Diagnostics
 *
 * Tests: SEO orchestrator health, health reports, pre-publication gate status,
 * schema.org markup, meta tag coverage.
 */

import type { DiagnosticResult } from "../types";

const SECTION = "seo";

function pass(id: string, name: string, detail: string, explanation: string): DiagnosticResult {
  return { id: `${SECTION}-${id}`, section: SECTION, name, status: "pass", detail, explanation };
}
function warn(id: string, name: string, detail: string, explanation: string, diagnosis?: string, fixAction?: DiagnosticResult["fixAction"]): DiagnosticResult {
  return { id: `${SECTION}-${id}`, section: SECTION, name, status: "warn", detail, explanation, diagnosis, fixAction };
}
function fail(id: string, name: string, detail: string, explanation: string, diagnosis?: string, fixAction?: DiagnosticResult["fixAction"]): DiagnosticResult {
  return { id: `${SECTION}-${id}`, section: SECTION, name, status: "fail", detail, explanation, diagnosis, fixAction };
}

const seoSection = async (
  siteId: string,
  _budgetMs: number,
  _startTime: number,
): Promise<DiagnosticResult[]> => {
  const results: DiagnosticResult[] = [];

  // ── 1. SEO Standards Version ───────────────────────────────────────
  try {
    const { STANDARDS_VERSION, CONTENT_QUALITY, ALGORITHM_CONTEXT } = await import("@/lib/seo/standards");
    results.push(pass("standards-version", "SEO Standards Version", `v${STANDARDS_VERSION}`, "The centralized SEO standards file defines all quality thresholds. Keeping it up-to-date ensures your content meets current Google requirements."));

    if (ALGORITHM_CONTEXT.authenticityUpdateActive) {
      results.push(pass("authenticity-update", "Jan 2026 Authenticity Update", "Active — first-hand experience checks enabled", "Google's January 2026 core update prioritizes first-hand experience as the #1 E-E-A-T signal. Your content generation prompts and quality gate enforce authenticity markers."));
    }

    results.push(pass("quality-thresholds", "Quality Gate Thresholds", `Min words: ${CONTENT_QUALITY.minWords}, SEO gate: ${CONTENT_QUALITY.qualityGateScore}, Meta desc: ${CONTENT_QUALITY.metaDescriptionMin}-160`, "Current quality gate settings. These thresholds determine whether an article passes the pre-publication gate and gets published."));
  } catch {
    results.push(warn("standards-version", "SEO Standards", "Could not load standards.ts", "The SEO standards file should be loadable for quality enforcement."));
  }

  // ── 2. SEO Reports in Database ─────────────────────────────────────
  try {
    const { prisma } = await import("@/lib/db");

    // Check for recent SEO reports
    const recentReports = await prisma.seoReport.findMany({
      where: { site_id: siteId },
      orderBy: { generatedAt: "desc" },
      take: 3,
      select: { id: true, reportType: true, generatedAt: true },
    });

    if (recentReports.length > 0) {
      const latest = recentReports[0];
      const ageHours = Math.round((Date.now() - new Date(latest.generatedAt).getTime()) / (1000 * 60 * 60));
      results.push(pass("seo-reports", "SEO Reports", `${recentReports.length} report(s) — latest: ${ageHours}h ago (type: ${latest.reportType})`, "SEO reports are generated by the weekly orchestrator. They track your site's search health over time and flag issues that need attention."));
    } else {
      results.push(warn("seo-reports", "SEO Reports", "No SEO reports found", "SEO reports are generated by the weekly orchestrator.", "The SEO orchestrator may not have run yet. Check the cron schedule.", {
        id: "fix-no-seo-reports",
        label: "Run SEO Orchestrator",
        api: "/api/cron/seo-orchestrator",
        rerunGroup: "seo",
      }));
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (!msg.includes("P2021")) {
      results.push(warn("seo-reports", "SEO Reports", `Error: ${msg}`, "Checks for SEO report history."));
    }
  }

  // ── 3. Pre-Publication Gate (14 checks) ────────────────────────────
  results.push(pass("prepub-gate", "Pre-Publication Gate", "14 quality checks active", "Every article must pass 14 checks before publishing: route existence, Arabic route, SEO minimums, SEO score (blocks <50), heading hierarchy, word count (1,000+), internal links (3+), readability, image alt text, author attribution, structured data, authenticity signals, affiliate links, and AIO readiness."));

  // ── 4. Content Quality Sample ──────────────────────────────────────
  try {
    const { prisma } = await import("@/lib/db");

    const recentPosts = await prisma.blogPost.findMany({
      where: { siteId, status: "published" },
      orderBy: { published_at: "desc" },
      take: 10,
      select: {
        id: true,
        slug: true,
        seo_score: true,
        word_count_en: true,
        meta_title_en: true,
        meta_description_en: true,
        content_en: true,
      },
    });

    if (recentPosts.length > 0) {
      // Meta title length check
      const badTitles = recentPosts.filter(p => {
        const len = (p.meta_title_en || "").length;
        return len < 30 || len > 60;
      });
      if (badTitles.length === 0) {
        results.push(pass("meta-titles", "Meta Title Lengths", "All recent articles have titles 30-60 chars", "Meta titles should be 30-60 characters. Too short = missed opportunity; too long = Google truncates them in search results."));
      } else {
        results.push(warn("meta-titles", "Meta Title Lengths", `${badTitles.length}/${recentPosts.length} articles have bad title lengths`, "Meta titles should be 30-60 characters.", "Some meta titles are too short or too long. The SEO agent can auto-fix these.", {
          id: "fix-meta-titles",
          label: "Auto-Fix Meta Titles",
          api: "/api/cron/seo-agent",
          rerunGroup: "seo",
        }));
      }

      // Meta description length check
      const badDescs = recentPosts.filter(p => {
        const len = (p.meta_description_en || "").length;
        return len < 120 || len > 160;
      });
      if (badDescs.length === 0) {
        results.push(pass("meta-descs", "Meta Description Lengths", "All recent articles have descriptions 120-160 chars", "Meta descriptions should be 120-160 characters. This is the text shown in Google search results — it's your sales pitch to searchers."));
      } else {
        results.push(warn("meta-descs", "Meta Description Lengths", `${badDescs.length}/${recentPosts.length} articles have bad description lengths`, "Meta descriptions should be 120-160 characters.", "Some descriptions are too short or too long. The SEO agent can auto-trim/generate these.", {
          id: "fix-meta-descs",
          label: "Auto-Fix Meta Descriptions",
          api: "/api/cron/seo-agent",
          rerunGroup: "seo",
        }));
      }

      // Internal links check
      const lowLinks = recentPosts.filter(p => {
        const content = p.content_en || "";
        const linkCount = (content.match(/<a\s+[^>]*href="[^"]*"/g) || []).length;
        return linkCount < 3;
      });
      if (lowLinks.length === 0) {
        results.push(pass("internal-links", "Internal Links", "All recent articles have 3+ internal links", "Internal links connect your articles and help Google understand your site structure. 3+ per article is the minimum for topical authority."));
      } else {
        results.push(warn("internal-links", "Internal Links", `${lowLinks.length}/${recentPosts.length} articles have fewer than 3 internal links`, "Internal links help Google understand site structure and build topical authority.", "The SEO agent can auto-inject related article links.", {
          id: "fix-internal-links",
          label: "Run SEO Agent (Link Injection)",
          api: "/api/cron/seo-agent",
          rerunGroup: "seo",
        }));
      }

      // Heading hierarchy check
      const badHeadings = recentPosts.filter(p => {
        const content = p.content_en || "";
        const h1Count = (content.match(/<h1[\s>]/g) || []).length;
        const h2Count = (content.match(/<h2[\s>]/g) || []).length;
        return h1Count > 1 || h2Count < 2;
      });
      if (badHeadings.length === 0) {
        results.push(pass("heading-hierarchy", "Heading Hierarchy", "All recent articles have proper heading structure", "Proper heading hierarchy (1 H1, 2+ H2s, no skipped levels) helps Google understand your content structure and improves readability."));
      } else {
        results.push(warn("heading-hierarchy", "Heading Hierarchy", `${badHeadings.length}/${recentPosts.length} articles have heading issues`, "Proper heading hierarchy helps Google understand content structure.", "Some articles have multiple H1 tags or too few H2 sections."));
      }
    }
  } catch {
    results.push(warn("content-quality", "Content Quality", "Could not sample content quality", "Checks SEO compliance of recent articles."));
  }

  // ── 5. Schema.org Structured Data ──────────────────────────────────
  results.push(pass("schema-types", "Structured Data Types", "Article, Organization, WebSite, BreadcrumbList, Product, Place, Trip, FAQPage", "Your site uses 8 JSON-LD schema types across different page types. This tells Google exactly what each page is about, enabling rich snippets in search results."));

  // ── 6. Deprecated Schema Check ─────────────────────────────────────
  results.push(pass("schema-deprecated", "Deprecated Schema", "FAQPage (restricted) and HowTo (deprecated) correctly blocked", "Google deprecated HowTo schema in Sept 2023 and restricted FAQPage in Aug 2023. Your schema generator correctly falls back to Article type for these pages."));

  return results;
};

export default seoSection;
